### ISSUE TITLE
error in get_user_timeline

### ISSUE THREAD

**Issue by lizmckenna** [snfagora/CivicTwitter#2]
https://github.com/snfagora/CivicTwitter/blob/dd5c526f55161d2bb42aab0f0f5df4637302e3b9/R/twitter.R#L175

@milandv I hope I'm doing this right...this is the error I got when trying to call this function: Error in get_user_timeline("26657119") : object 'res' not found

**Comment by lizmckenna** [comment]
@milandv I reinstalled the latest version of the package and this time when I ran this function I got the Joining, by output, but still got the 'object 'res' error below...thoughts?

`> df2 <- get_user_timeline("26657119")
Joining, by = "document.id"
Error in get_user_timeline("26657119") : object 'res' not found`

**Comment by milandv** [comment]
Yeah, I'm reopening this issue. There's a problem at the moment on the twitter end. The pagination token that the API call returns is long but then when you request the next page it complains that the pagination_token should only be 16 characters. Can't have it both ways, BirdPeople.

````$errors
$errors[[1]]
$errors[[1]]$parameters
$errors[[1]]$parameters$pagination_token
$errors[[1]]$parameters$pagination_token[[1]]
[1] "7140dibdnow9c7btw3w3y5b6i8k4wmx8tilvxunk3hnw9"



$errors[[1]]$message
[1] "The length of the `pagination_token` query parameter [45] is not between 16 and 16"


$errors[[2]]
$errors[[2]]$parameters
$errors[[2]]$parameters$pagination_token
$errors[[2]]$parameters$pagination_token[[1]]
[1] "7140dibdnow9c7btw3w3y5b6i8k4wmx8tilvxunk3hnw9"
```
